version: '3'

services:
  bedrock_server:
    image: bedrock_server:latest
    container_name: bedrock_server
    environment:
# Update this as the file changes.  Please be sure to agree to the EULA
      - BEDROCK_DOWNLOAD_ZIP=https://minecraft.azureedge.net/bin-linux/bedrock-server-1.7.0.13.zip
    ports: 
      - 19132:19132/udp
#      - 19133:19133/udp
    stdin_open: true
    tty: true
    volumes:
      - ./data/worlds:/home/bedrock/bedrock_server/worlds
      - ./data/server.properties:/home/bedrock/bedrock_server/server.properties
      - ./data/ops.json:/home/bedrock/bedrock_server/ops.json
      - ./data/whitelist.json:/home/bedrock/bedrock_server/whitelist.json
